FROM php:7.1-fpm
LABEL maintainer="jimmy <gao1963bin@gmail.com>"

# 安装 git curl vim zip
RUN apt-get update && apt-get install -y libzip-dev git vim curl libfreetype6-dev \
    && rm -rf /var/lib/apt/lists/* \
    && pecl install zip \
    && docker-php-ext-enable zip

RUN git config --global user.name 'jimmy' \
 && git config --global user.email "gao1963bin@gmail.com"

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
 && php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
 && php composer-setup.php \
 && php -r "unlink('composer-setup.php');" \
 && mv composer.phar /usr/local/bin/composer \
 && echo 'export PATH="$PATH/.composer/vendor/bin"' >> ~/.bashrc \
 && . ~/.bashrc